### PR TITLE
fix some bug and add some new feature

### PR DESCRIPTION
**Pull request by onedou**
fix some bug and add some new feature

### CODE REVIEW

**Comment by LiXizhi** [comment]
it is too big put all mod files  in the main wikicraft repo.  
Can you only put a release file like `draw.io` and move all dev files to a separate repo like the relationship of worldshare and paracraft. 

BTW, I wonder if it is possible to display a progress bar when downing the 1MB js file.

**Comment by onedou** [comment]
ok,I will push only rls files to repo.
should I find another progress bar js program?

**Comment by onedou** [comment]
ok,I will push only rls files to repo.
should I find another progress bar js program?

**Comment by LiXizhi** [comment]
I think the standard loading gif used elsewhere in keepwork is enough

**Comment by onedou** [comment]
ok, I use standard loading gif.

**Pull request closed without merging**
